version: '3.8'

services:
 web:
  build: .
  command: python manage.py runserver 0.0.0.0:8000
  volumes:
   - .:/app
   - C:/Users/User/Downloads/ancient-tractor-455208-t5-82585cd5330b.json:/app/service-account-key.json:ro # Mount the key securely

  ports:
   - "8000:8000"
  environment:
   - DEBUG=1
   - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account-key.json # Point to the mounted file within the container
